version: "3"

services:

  runtime-setup:
    image: netty:centos-6-1.15
    build:
      args:
        centos_version : "6"
        # use zulu and not adoptjdk for now as adoptjdk15 does not support centos6
        # https://github.com/AdoptOpenJDK/openjdk-build/issues/2097
        java_version : "zulu@1.15.0-1"

  test:
    image: netty:centos-6-1.15

  test-leak:
    image: netty:centos-6-1.15

  test-boringssl-static:
    image: netty:centos-6-1.15

  shell:
    image: netty:centos-6-1.15
